### PR TITLE
Use installed protoc first

### LINKED ISSUE #284: Timeout while downloading protobuf Compiler
## Report
```console
thread 'main' panicked at /Users/ares/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/rinf-6.1.0/src/main.rs:13:65:
called `Result::unwrap()` on an `Err` value: Ureq(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-osx-aarch_64.zip", query: None, fragment: None }), source: Some(Error { kind: TimedOut, message: "connection timed out" }) }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
## Steps to Reproduce

_Please describe the exact steps to reproduce the error._

## System Information

_Please provide the output from the command below, using markdown codeblock syntax._

```bash
rustc --version
flutter doctor
```

### PR DESCRIPTION
**Pull request by andrew-ares**
## Summary
<del>
This PR introduces a flag `--protoc-path` (short: `-p`), allowing users to specify the protoc path. This is particularly useful for developers in China that unable to directly download binaries from GitHub, as they face restrictions imposed by the [Great Firewall](https://en.wikipedia.org/wiki/Great_Firewall). Therefore, when they initially use rinf, the installation action may timeout, resulting in the following error:

```console
$ thread 'main' panicked at /Users/ares/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/rinf-6.1.0/src/main.rs:13:65:
called `Result::unwrap()` on an `Err` value: Ureq(Transport(Transport { kind: ConnectionFailed, message: Some("Connect error"), url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-osx-aarch_64.zip", query: None, fragment: None }), source: Some(Error { kind: TimedOut, message: "connection timed out" }) }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
With this PR merged, one can use rinf like this:

```console
$ rinf message -p $(dirname $(which protoc))
```
</del>

Detecting the installed protoc instead of default downloading is helpful in addressing network restrictions, particularly the [problem](https://en.wikipedia.org/wiki/Great_Firewall) faced by developers in China.

## Changes

Fixes #284

## Before Committing

_Please make sure that you've analyzed and formatted the files._

```
dart analyze flutter_ffi_plugin --fatal-infos
dart format .
cargo fmt
cargo clippy --fix --allow-dirty
```

### CODE REVIEW

**Comment by temeddix** [comment]
Thanks! I will review this and publish a new version soon.

File: rust_crate/src/main.rs [hunk 1]
```diff
@@ -1,17 +1,37 @@
...
-    fs::create_dir_all(&out_path).unwrap();
-    env::set_var("OUT_DIR", out_path.to_str().unwrap());
-    let (protoc_binary_path, _) = protoc_prebuilt::init("25.2").unwrap();
-    let protoc_path = protoc_binary_path.parent().unwrap().to_path_buf();
+    let args = Args::parse();
+
+    let protoc_path;
+
+    if let Some(p) = args.protoc_path {
+        let provided = PathBuf::from_str(&p).unwrap();
```
Comment (andrew-ares) [inline rust_crate/src/main.rs]: Is it worth to add a check for path existence here? Like:
```rust
if !provided.exists() {
// inform an error
}
```

Comment (temeddix) [reply rust_crate/src/main.rs]: Yeah, I think it's a good idea to do it :)

Comment (andrew-ares) [reply rust_crate/src/main.rs]: Done

**Comment by temeddix** [comment]
By the way, may I ask which parts of GitHub can Chinese developers access? I've seen many Chinese developers here, but is downloading files from GitHub prohibited, or GitHub APIs?

**Comment by andrew-ares** [comment]
There's no certain answer for this. Some repo can be accessed. But it really depends on the mood of the GFW. AFAIK, downloading files from GitHub has always been problematic.

**Comment by temeddix** [comment]
Let me share that I came up with one question.

Users can install protoc on their machine manually, and they can add their protoc to PATH.

Why don't we just make `protoc_prebuilt` bypass automatic installation of protoc, if it's already in PATH? That could be a cleaner and elegant solution.

This way, we don't need to use `clap` at all. Would you consider changing the PR this way? If you do, I'll be adding this info to the docs.

**Comment by andrew-ares** [comment]
Yeah, that makes sense too.

> This way, we don't need to use clap at all. Would you consider changing the PR this way?

Sure. I will make a change later.

**Comment by temeddix** [comment]
Thanks for your kind consideration :)

**Comment by andrew-ares** [comment]
@temeddix Would you like to take another review on this?

**Comment by temeddix** [comment]
Sure, I'm out right now, so I'll take a look in a few hours. Please hold on.

**Review by temeddix — APPROVED** [review]

**Comment by temeddix** [comment]
Thank you very much :) Feel free to come back if you have any other issues!
