### PR TITLE
log an error if the binding is not ready

### LINKED ISSUE #460: Error when running example on Flutter web
## Report

I encountered an error when running the example from the RInf repository on the web. 

Here is the error I received:

```
eferenceError: rinf is not defined
pkg/hub.js 619:70    __wbg_get_imports
pkg/hub.js 878:21    __wbg_init
```

The example works fine on iOS.

Seems like the problem occurs by the generated file generates from `rinf wasm`

I'm currently using
rustc 1.81.0
Flutter:
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-TH)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    ✗ Unable to get list of installed Simulator runtimes.
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see https://guides.cocoapods.org/using/getting-started.html#installation
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.1)
[✓] Connected device (3 available)
[✓] Network resources
```

### PR DESCRIPTION
**Pull request by poborin**
## Changes
catch a JS error if the binding is not ready. Fixes #460

### CODE REVIEW

**Comment by temeddix** [comment]
Thanks for your contribution :)

May I ask you if this fixes #460, or it just kindly prints an error if binding is not ready? It looks like code just handles error gracefully to me.

----------

After some debugging, now I see what this PR does. When there is no global `rinf` JS object, your code might be able to ignore the absense and proceed, even in web workers. Thanks a lot.

File: rust_crate/src/interface_web.rs [hunk 1]
```diff
@@ -22,23 +22,28 @@ where
...
         message_id,
         js_sys::Uint8Array::from(message_bytes.as_slice()),
         js_sys::Uint8Array::from(binary.as_slice()),
-    );
-    Ok(())
+    ) {
+        Ok(_) => Ok(()),
+        Err(e) => {
+            crate::debug_print!("An error occured during the launch: {e:?}");
+            Err(RinfError::NoSignalHandler)
```
Comment (temeddix) [inline rust_crate/src/interface_web.rs:46]: Do you mind adding a separate error variant, maybe `RinfError::NoBinding`?

**Review by temeddix — APPROVED** [review]

**Comment by temeddix** [comment]
I'll publish a new version within a day. Thank you very much
